language: generic
cache:
  directories:
  - "$HOME/.stack"
env:
- GHCVER=8.4.4 STACK_YAML=stack.yaml
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps --coverage
after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2
  | tar -xj
- "./shc slack-verify slack-verify-test"
after_success:
- stack install cabal-install

deploy:
  skip_cleanup: true
  provider: hackage
  username: kkweon
  password:
    secure: XfHopU4oCRO9DejJVBNpyrRq8X3oMC+kv3b/mH/pW2sEZef4EHICM5c62LkgRfVswZEVLQJ4w15sMwe6+1wlIfqyYjHLyzpd+vWwvgnaMFT+EAWkVfA29U8IQa56QGsygU5RoOKMbXj6ZjnRoxk1ShCriVvutr4yBF54ch1Q08qEk/8u74duyHeMxJ9AQ1dT61qnAXmIM3Rq0xJ2iiPPsRCy3pon+WWviJ1nduurBaIiiSpYoxYkPzDrORB7et6XeXojH9Nd0v8xxslVY1rjo2I2OgpdaufEaLxIwSLPy3sv3RlHXlchyVAoFQc1K1t+z8N3G8BtaolHXPmhN/0RAa2A03cd6dJTmyFwBk1I0CmTZasXjDumUlt15pmgYfVs4POhII/UdRGaNrA0DQXdSwcAKFFqGafKHUYvI5F6sq7uRoBQzsy020/cnDN2yWFNlAgcdmgfud/HJwWn8wZpO3UwZv7QIi0qDp1Sier2W7YjjueSn3DEDH0xd83P5fDKMFmVrSnZckeO6YbHFtScFaNAS7nuH3GU0uqEfDBGTq90GI6Rgxnb29/Tf37zNZmf/Nl+mYydP37qImWO0QamWxT9RF0qho3fRZssrS49NBk3UnHb1yaQe6LeMXvb+CjyIN+I/XrawY2tKFZP5GY06wiU4+lgMCTP/x/Tla7dOb0=
  on:
    repo: kkweon/slack-verify-haskell
    branch: master
