language: generic
cache:
  directories:
  - "$HOME/.stack"
env:
- GHCVER=8.4.4 STACK_YAML=stack.yaml

addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar
  xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --no-terminal test --haddock --no-haddock-deps --coverage
after_script:
- travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar -xj
- ./shc slack-verify slack-verify-test

after_success:
- stack install cabal-install

deploy:
  skip_cleanup: true
  provider: hackage
  username: kkweon
  password:
    secure: KHd4W2MLD/HYyr7MhHbZR64PssZANhPQsogSoPoAuawRLRo1uzIPuVTOKkQkC8p7oY1HwJ6kv8jbOJC6SPMZRe04YxvMaFwrT7so+sohW2cx6TS1VBOWUqZbjOKQgKmZCp6JLVRQr+mtKfJXVskLjAKDwLFhp8/yfbFzegkDqHJ1ph2Q0upL8KEZ/RGhmc0iDxntd7WC01TJG5GDexBR2mnVg685YKxgzBXGAUrk8y9NJn81p3K2VeGOGTuY2J3x2e1YJBxFqpORr4xm8CrFNVCx+/mWSr9i9UvVPHyBiKhGfypHsK7WOPbvUUoHnms3B2YTHddkM6xPdy8cSmQPcyN+YEp+s06mk6swwOQGWtGuEosHL7r4ZqRWZrvFE2CZ/7zspM2L9FlPHfQJVzhc/ncrzKJTwBBHI7DPSFJ30DwTGuP7c8l3+e2U8bxWLTlY8Kw7dAHhf2zK0rEr1xguPVx3ngzxwe1VOsxbh3cuS3WM2f5AL1Uq9Ddn7nnKgpkV+Jv1NTi72xHbrEdS1MxUywIE+IKtoKD7kq7F8bTz/me2JnLWBqXGjWi4MssDt2oruVCzg5UyaXNxHijZLOgSoayg6h4Sb+WcUN1qTzJXpeyvLhj3UNdfHbwHUzH5C2eEgaa9eeKfsXm0Ys6rA6UCnFaJYNR0WS8VFfBUnb0OFY4=
  on:
    repo: kkweon/slack-verify-haskell
    branch: master
